### ISSUE TITLE
Segmentation fault when restoring backup

### ISSUE THREAD

**Issue by rubencm** [gogs/gogs#4797]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

- Gogs version (or commit ref): 0.11.19
- Git version: 
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
  - Empty

## Description
I am having this error after install gogs from the ubuntu deb package.
The backup has been made from a raspberry.

```
apt install gogs
useradd -m git
su git
```

```
git@server:/opt/gogs$ ./gogs restore --from="gogs-backup-20170924213133.zip" --verbose
Unzipping gogs-backup-20170924213133.zip...
Extracting file...gogs-backup/
Extracting file...gogs-backup/metadata.ini
Extracting file...gogs-backup/repositories.zip
2017/09/24 21:59:17 [ INFO] Restore backup from: gogs-backup-20170924213133.zip
Extracting file...gogs-backup/data/
Extracting file...gogs-backup/data/avatars/
Extracting file...gogs-backup/data/avatars/3
Extracting file...gogs-backup/data/avatars/1
Extracting file...gogs-backup/db/
Extracting file...gogs-backup/db/EmailAddress.json
Extracting file...gogs-backup/db/TwoFactor.json
Extracting file...gogs-backup/db/PullRequest.json
Extracting file...gogs-backup/db/AccessToken.json
Extracting file...gogs-backup/db/Version.json
Extracting file...gogs-backup/db/ProtectBranchWhitelist.json
Extracting file...gogs-backup/db/PublicKey.json
Extracting file...gogs-backup/db/Notice.json
Extracting file...gogs-backup/db/Team.json
Extracting file...gogs-backup/db/TwoFactorRecoveryCode.json
Extracting file...gogs-backup/db/Access.json
Extracting file...gogs-backup/db/Issue.json
Extracting file...gogs-backup/db/Upload.json
Extracting file...gogs-backup/db/HookTask.json
Extracting file...gogs-backup/db/Action.json
Extracting file...gogs-backup/db/Repository.json
Extracting file...gogs-backup/db/IssueUser.json
Extracting file...gogs-backup/db/Star.json
Extracting file...gogs-backup/db/Label.json
Extracting file...gogs-backup/db/Webhook.json
Extracting file...gogs-backup/db/Mirror.json
Extracting file...gogs-backup/db/TeamRepo.json
Extracting file...gogs-backup/db/User.json
Extracting file...gogs-backup/db/Follow.json
Extracting file...gogs-backup/db/Milestone.json
Extracting file...gogs-backup/db/Attachment.json
Extracting file...gogs-backup/db/ProtectBranch.json
Extracting file...gogs-backup/db/LoginSource.json
Extracting file...gogs-backup/db/Release.json
Extracting file...gogs-backup/db/Watch.json
Extracting file...gogs-backup/db/DeployKey.json
Extracting file...gogs-backup/db/Comment.json
Extracting file...gogs-backup/db/IssueLabel.json
Extracting file...gogs-backup/db/TeamUser.json
Extracting file...gogs-backup/db/Collaboration.json
Extracting file...gogs-backup/db/OrgUser.json
Extracting file...gogs-backup/custom/
Extracting file...gogs-backup/custom/conf/
Extracting file...gogs-backup/custom/conf/app.ini
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x80274d]

goroutine 1 [running]:
github.com/gogits/gogs/vendor/github.com/go-xorm/xorm.(*Session).Begin(0xc420080480, 0xef6c98, 0xc420080480)
	/tmp/tmp.722mEjnAYT/.go/src/github.com/gogits/gogs/vendor/github.com/go-xorm/xorm/session_tx.go:10 +0x10d
github.com/gogits/gogs/vendor/github.com/go-xorm/xorm.(*Engine).DropTables(0x0, 0xc4200933e8, 0x1, 0x1, 0x0, 0x0)
	/tmp/tmp.722mEjnAYT/.go/src/github.com/gogits/gogs/vendor/github.com/go-xorm/xorm/engine.go:1329 +0x84
github.com/gogits/gogs/models.ImportDatabase(0xc4205e3e60, 0x13, 0x1, 0xc4205e3e01, 0x13)
	/tmp/tmp.722mEjnAYT/.go/src/github.com/gogits/gogs/models/models.go:314 +0x372
github.com/gogits/gogs/cmd.runRestore(0xc420434140, 0x100, 0xc420434140)
	/tmp/tmp.722mEjnAYT/.go/src/github.com/gogits/gogs/cmd/restore.go:86 +0x7cf
github.com/gogits/gogs/vendor/github.com/urfave/cli.HandleAction(0xd94b60, 0xef5558, 0xc420434140, 0xc420424400, 0x0)
	/tmp/tmp.722mEjnAYT/.go/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/app.go:483 +0xb9
github.com/gogits/gogs/vendor/github.com/urfave/cli.Command.Run(0xeb36c4, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xeddec2, 0x26, 0x0, ...)
	/tmp/tmp.722mEjnAYT/.go/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/command.go:193 +0xb72
github.com/gogits/gogs/vendor/github.com/urfave/cli.(*App).Run(0xc4200f1ba0, 0xc420010180, 0x4, 0x4, 0x0, 0x0)
	/tmp/tmp.722mEjnAYT/.go/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/app.go:250 +0x7d0
main.main()
	/tmp/tmp.722mEjnAYT/.go/src/github.com/gogits/gogs/gogs.go:41 +0x3ea
```

**Comment by matlink** [comment]
Looks like the gogs binary has not been compiled with sqlite support.

**Comment by rubencm** [comment]
Ok, thanks. This is from the packager.io repository, i didn't compiled it.

**Comment by matlink** [comment]
Maybe you can find an sqlite-enabled version of it somewhere.

**Comment by Unknwon** [comment]
Hi, is this still happening with latest release (0.11.53) of Gogs?

**Comment by rubencm** [comment]
Sorry, i don't have that backup from the raspberry anymore

**Comment by Unknwon** [comment]
Hmm, well. Feel free to report back when this happens again.
