### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kylebarron** [gogs/gogs#5486]
- Gogs version (or commit ref): 0.11.66
- Git version: git version 2.10.1.352.g0cf3611
- Operating system: Scientific Linux 6 (RHEL 6)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): below after stdout trace

## Description

Gogs crashed while making a pull request. This happened on two separate occasions for two separate users of the system. On both occasions, restarting Gogs and attempting the PR again succeeded. This may be similar to https://github.com/gogs/gogs/issues/4883. However that was closed and of a previous version of Gogs, so this is probably a different bug.

Stdout:
```
[Macaron] 2018-10-30 15:12:51: Started GET /daltonm/medicare-documentation/commit/e4cfb62a6a93e0f0033999dd42a0d254b3d74661 for 10.200.10.2
[Macaron] 2018-10-30 15:12:52: Completed GET /daltonm/medicare-documentation/commit/e4cfb62a6a93e0f0033999dd42a0d254b3d74661 200 OK in 387.942988ms
[Macaron] 2018-10-30 15:12:55: Started GET /daltonm/medicare-documentation/commit/e91a16ec5c07634704e16068d7637851e6eeb3ad for 10.200.10.2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x88d4ec]

goroutine 6078 [running]:
github.com/gogs/gogs/vendor/github.com/gogs/git-module.ParsePatch(0xc4223d4f00, 0x3e8, 0x1f4, 0x64, 0x1109de0, 0xc4220989e0, 0xc4223d4d80)
        /home/vagrant/gopath/src/github.com/gogs/gogs/vendor/github.com/gogs/git-module/repo_diff.go:178 +0x2fc
github.com/gogs/gogs/vendor/github.com/gogs/git-module.GetDiffRange.func1(0xc4223d4f00, 0x3e8, 0x1f4, 0x64, 0xc4220989e0, 0xc4220989f0)
        /home/vagrant/gopath/src/github.com/gogs/gogs/vendor/github.com/gogs/git-module/repo_diff.go:336 +0x63
created by github.com/gogs/gogs/vendor/github.com/gogs/git-module.GetDiffRange
        /home/vagrant/gopath/src/github.com/gogs/gogs/vendor/github.com/gogs/git-module/repo_diff.go:335 +0x322
```

Log (without CSRF token lines):
```
2018/10/30 15:12:36 [TRACE] Template: repo/pulls/compare
2018/10/30 15:12:39 [TRACE] Session ID: 998fc15e7021affa
2018/10/30 15:12:39 [TRACE] Template: repo/pulls/compare
2018/10/30 15:12:51 [TRACE] Session ID: 998fc15e7021affa
2018/10/30 15:12:52 [TRACE] Template: repo/diff/page
2018/10/30 15:12:55 [TRACE] Session ID: 998fc15e7021affa
2018/10/30 15:14:17 [TRACE] Log Mode: File (Trace)
```

**Comment by tienli** [comment]
Same error. It's upon the first run and visit. Tried to install and panic happened. Here is the error message
 [Macaron] PANIC: runtime error: invalid memory address or nil pointer dereference
runtime/panic.go:221 (0x4db27)
runtime/signal_unix.go:735 (0x69847)
gogs.io/gogs/internal/route/repo/http.go:66 (0xb6c9d8)
gopkg.in/macaron.v1@v1.3.9/context.go:79 (0x3c6fa7)
github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:157 (0x39ddcf)
github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:135 (0x39dd23)
gopkg.in/macaron.v1@v1.3.9/context.go:121 (0x3c70eb)
gopkg.in/macaron.v1@v1.3.9/context.go:112 (0x3d73df)
gopkg.in/macaron.v1@v1.3.9/recovery.go:161 (0x3d73c8)
gopkg.in/macaron.v1@v1.3.9/logger.go:40 (0x3ca41b)
github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:157 (0x39ddcf)
github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:135 (0x39dd23)
gopkg.in/macaron.v1@v1.3.9/context.go:121 (0x3c70eb)
gopkg.in/macaron.v1@v1.3.9/router.go:187 (0x3d13cf)
gopkg.in/macaron.v1@v1.3.9/router.go:303 (0x3d22d7)
gopkg.in/macaron.v1@v1.3.9/macaron.go:220 (0x3cb65b)
net/http/server.go:2879 (0x34dc73)
net/http/server.go:1930 (0x349e3b)
runtime/asm_arm.s:838 (0x85d8f)
