### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference (v0.11.79.1211) mysql5.6

### ISSUE THREAD

**Issue by onigm** [gogs/gogs#5589]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb91766]

goroutine 3858 [running]:
github.com/gogs/gogs/models.(*Repository).getOwner(0x0, 0x111fa80, 0xc4201ba0d0, 0x100000000000037, 0x0)
        /home/vagrant/gopath/src/github.com/gogs/gogs/models/repo.go:399 +0x26
github.com/gogs/gogs/models.(*Repository).mustOwner(0x0, 0x111fa80, 0xc4201ba0d0, 0x0)
        /home/vagrant/gopath/src/github.com/gogs/gogs/models/repo.go:412 +0x43
github.com/gogs/gogs/models.(*Repository).repoPath(0x0, 0x111fa80, 0xc4201ba0d0, 0x2, 0x2)
        /home/vagrant/gopath/src/github.com/gogs/gogs/models/repo.go:532 +0x43
github.com/gogs/gogs/models.(*Repository).RepoPath(0x0, 0x44, 0xc4230f1ce0)
        /home/vagrant/gopath/src/github.com/gogs/gogs/models/repo.go:536 +0x43
github.com/gogs/gogs/models.(*PullRequest).PushToBaseRepo(0xc422038620, 0x0, 0x0)
        /home/vagrant/gopath/src/github.com/gogs/gogs/models/pull.go:639 +0x117
github.com/gogs/gogs/models.addHeadRepoTasks(0xc420aad9b0, 0x1, 0x2)
        /home/vagrant/gopath/src/github.com/gogs/gogs/models/pull.go:721 +0x143
github.com/gogs/gogs/models.AddTestPullRequestTask(0xc4232aa800, 0x7a, 0xc421b6d000, 0x6, 0xc4228d2300)
        /home/vagrant/gopath/src/github.com/gogs/gogs/models/pull.go:766 +0x587
created by github.com/gogs/gogs/models.(*PullRequest).Merge.func1
        /home/vagrant/gopath/src/github.com/gogs/gogs/models/pull.go:199 +0xc3

**Comment by onigm** [comment]
Mysql has been updated to 5.7, but will also crash
