### ISSUE TITLE
Crash when doing multiple simultaneous pulls over ssh

### ISSUE THREAD

**Issue by k3an3** [gogs/gogs#5735]
**Describe the bug**
When performing a project update with multiple repositories using PyCharm 2019.1, the IDE attempts to update the projects in parallel. In one scenario, I have 3 repositories currently open in PyCharm, and it tries to pull from all 3 of them simultaneously. The first one succeeds, the other two result in a Go stack track and errors.

These 3 git commands were run simultaneously from their respective working directories:
```sh
/usr/bin/git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --progress --prune 
/usr/bin/git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --progress --prune 
/usr/bin/git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --progress --prune 
```

**To Reproduce**
1. Pull from multiple git repositories simultaneously
2. Receive errors from several of the pulls
3. Pull again, usually works fine (maybe since one has already been updated locally?)

**Expected behavior**
Repositories should be pulled with no error.

**Additional context**
Output from git commands:
```
 panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x71ee32] 
 goroutine 1 [running]: 
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x71ee32] 
 goroutine 1 [running]: 
 github.com/gogs/gogs/vendor/gopkg.in/clog%2ev1.(*file).deleteOutdatedFiles.func1(0xc420344ea0, 0x25, 0x0, 0x0, 0x11ccd00, 0xc4202e6960, 0x0, 0x0) 
 /home/vagrant/gopath/src/github.com/gogs/gogs/vendor/gopkg.in/clog.v1/file.go:139 +0x32 
 path/filepath.walk(0xc4202df840, 0x11, 0x11dabe0, 0xc42031f5f0, 0xc42028fb50, 0x0, 0x10) 
 /usr/local/go/src/path/filepath/path.go:377 +0x20d 
 path/filepath.Walk(0xc4202df840, 0x11, 0xc42028fb50, 0x11, 0x7) 
 /usr/local/go/src/path/filepath/path.go:403 +0x106 
 github.com/gogs/gogs/vendor/gopkg.in/clog%2ev1.(*file).deleteOutdatedFiles(0xc4200a6c00) 
 /home/vagrant/gopath/src/github.com/gogs/gogs/vendor/gopkg.in/clog.v1/file.go:138 +0xa3 
 github.com/gogs/gogs/vendor/gopkg.in/clog%2ev1.(*file).initRotate(0xc4200a6c00, 0x0, 0x0) 
 /home/vagrant/gopath/src/github.com/gogs/gogs/vendor/gopkg.in/clog.v1/file.go:190 +0x150 
 github.com/gogs/gogs/vendor/gopkg.in/clog%2ev1.(*file).Init(0xc4200a6c00, 0x103a100, 0xc4202494c0, 0x4, 0xc42008ef38) 
 /home/vagrant/gopath/src/github.com/gogs/gogs/vendor/gopkg.in/clog.v1/file.go:214 +0x286 
 github.com/gogs/gogs/vendor/gopkg.in/clog%2ev1.New(0x10eba17, 0x4, 0x103a100, 0xc4202494c0, 0x1a, 0x1c10060) 
 /home/vagrant/gopath/src/github.com/gogs/gogs/vendor/gopkg.in/clog.v1/logger.go:93 +0xb6 
 github.com/gogs/gogs/vendor/gopkg.in/clog%2ev1.(*file).deleteOutdatedFiles.func1(0xc42033ced0, 0x25, 0x0, 0x0, 0x11ccd00, 0xc4202e6960, 0x0, 0x0) 
 /home/vagrant/gopath/src/github.com/gogs/gogs/vendor/gopkg.in/clog.v1/file.go:139 +0x32 
 path/filepath.walk(0xc4200c9840, 0x11, 0x11dabe0, 0xc42019f5f0, 0xc420291b60, 0x0, 0x10) 
 /usr/local/go/src/path/filepath/path.go:377 +0x20d 
 path/filepath.Walk(0xc4200c9840, 0x11, 0xc420291b60, 0x11, 0x7) 
 /usr/local/go/src/path/filepath/path.go:403 +0x106 
 github.com/gogs/gogs/vendor/gopkg.in/clog%2ev1.(*file).deleteOutdatedFiles(0xc4200a6e80) 
 /home/vagrant/gopath/src/github.com/gogs/gogs/vendor/gopkg.in/clog.v1/file.go:138 +0xa3 
 github.com/gogs/gogs/vendor/gopkg.in/clog%2ev1.(*file).initRotate(0xc4200a6e80, 0x0, 0x0) 
 /home/vagrant/gopath/src/github.com/gogs/gogs/vendor/gopkg.in/clog.v1/file.go:190 +0x150 
 github.com/gogs/gogs/cmd.setup(0xc4200eca00, 0x10f2a66, 0x8, 0xc420249101) 
 /home/vagrant/gopath/src/github.com/gogs/gogs/cmd/serv.go:64 +0x1b8 
 github.com/gogs/gogs/cmd.runServ(0xc4200eca00, 0x0, 0xc4200eca00) 
 /home/vagrant/gopath/src/github.com/gogs/gogs/cmd/serv.go:126 +0x5d 
 github.com/gogs/gogs/vendor/gopkg.in/clog%2ev1.(*file).Init(0xc4200a6e80, 0x103a100, 0xc420247540, 0x4, 0xc42008ef38) 
 /home/vagrant/gopath/src/github.com/gogs/gogs/vendor/gopkg.in/clog.v1/file.go:214 +0x286 
 github.com/gogs/gogs/vendor/gopkg.in/clog%2ev1.New(0x10eba17, 0x4, 0x103a100, 0xc420247540, 0x1a, 0x1c10060) 
 /home/vagrant/gopath/src/github.com/gogs/gogs/vendor/gopkg.in/clog.v1/logger.go:93 +0xb6 
 github.com/gogs/gogs/cmd.setup(0xc42027a8c0, 0x10f2a66, 0x8, 0xc420247201) 
 /home/vagrant/gopath/src/github.com/gogs/gogs/cmd/serv.go:64 +0x1b8 
 github.com/gogs/gogs/cmd.runServ(0xc42027a8c0, 0x0, 0xc42027a8c0) 
 /home/vagrant/gopath/src/github.com/gogs/gogs/cmd/serv.go:126 +0x5d 
 github.com/gogs/gogs/vendor/github.com/urfave/cli.HandleAction(0xf64160, 0x113da98, 0xc42027a8c0, 0xc42007b200, 0x0) 
 /home/vagrant/gopath/src/github.com/gogs/gogs/vendor/github.com/urfave/cli/app.go:483 +0xad 
 github.com/gogs/gogs/vendor/github.com/urfave/cli.Command.Run(0x10ebd43, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1127422, 0x2f, 0x0, ...) 
 /home/vagrant/gopath/src/github.com/gogs/gogs/vendor/github.com/urfave/cli/command.go:193 +0xa35 
 github.com/gogs/gogs/vendor/github.com/urfave/cli.(*App).Run(0xc42009b520, 0xc4200300c0, 0x4, 0x4, 0x0, 0x0) 
 /home/vagrant/gopath/src/github.com/gogs/gogs/vendor/github.com/urfave/cli/app.go:250 +0x700 
 main.main() 
 /home/vagrant/gopath/src/github.com/gogs/gogs/gogs.go:40 +0x2b8 
 fatal: Could not read from remote repository. 
 Please make sure you have the correct access rights 
 and the repository exists. 
```

- Gogs version (or commit ref): 0.11.86.0130
- Git version: 2.20.1
- Operating system: Ubuntu 18.04
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [x] No: Not a web bug
- Log gist (usually found in `log/gogs.log`):

No new logs appear at time of bug.

**Comment by unknwon** [comment]
Thanks for the feedback!

The error comes from the logging package we use, I'll see what I can do.
