### ISSUE TITLE
Gogs doesnt start after upgrade, nothing in logs

### ISSUE THREAD

**Issue by Routhgen** [gogs/gogs#5781]
**Describe the bug**
Folowing official upgrade doc doesnt work and gogs wont start, no error logs

**To Reproduce**
1. I followed docs for [upgrade](https://gogs.io/docs/upgrade/upgrade_from_binary)
2. Process is pretty simple, everything was fine till start
3. /etc/init.d/gogs start do nothing, status after start/restart returns fail
4. ./gogs web return just this:
`$ ./gogs web`
`2019/08/14 10:54:37 [TRACE] Custom path: /opt/gogs/custom`
`2019/08/14 10:54:37 [TRACE] Log path: /opt/gogs/log`
`2019/08/14 10:54:37 [TRACE] Log Mode: File (Info)`
`2019/08/14 10:54:37 [ INFO] DATA 0.11.91.0811`

nothing more
logs are empty after stop&upgrade

When deleting upgraded gogs folder and replacing with original one from backup runs back again so the problem should be somewhere in new files.

**Additional context**

- Gogs version (or commit ref): from 0.11.4 to 0.11.91
I also tried upgrade to 0.11.53 to eliminate such a jump between versions but no luck at all (same behavior)
- Git version: 2.11
- Operating system: Debian 8 Jessie amd64
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [x] No: no GUI
- Log gist (usually found in `log/gogs.log`):
empty after upgrade

Thanks

**Comment by unknwon** [comment]
Hi, your log is here:
![image](https://user-images.githubusercontent.com/2946214/63048686-e1d3da80-be8b-11e9-98da-df8ddb708fe6.png)

**Comment by GramThanos** [comment]
I have the same problem with my Raspberry Pi 3.

Software info
```
$ uname -a
Linux dinotron 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
$ cat /etc/debian_version
9.9
```

GOGS Version (just after decompressing)
File `https://dl.gogs.io/0.11.91/gogs_0.11.91_raspi_armv7.zip`
```
$ ./gogs --version
Gogs version 0.11.91.0811
```

The installation does not provide an SQLite3 option
![image](https://user-images.githubusercontent.com/14858959/64085710-090c2200-cd3d-11e9-8707-bf1df041d5d8.png)

Restoring from backup zip throw error
```
$ ./gogs restore --from=/<path-to-usb-stick>/gogs-backup-20190902035631.zip
2019/09/02 04:50:22 [ INFO] Restore backup from: /<path-to-usb-stick>/gogs-backup-20190902035631.zip
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x37509c]

goroutine 1 [running]:
github.com/gogs/gogs/vendor/github.com/go-xorm/xorm.(*Session).DB(...)
        /home/pi/gopath/src/github.com/gogs/gogs/vendor/github.com/go-xorm/xorm/session.go:241
github.com/gogs/gogs/vendor/github.com/go-xorm/xorm.(*Session).Begin(0x118e0420, 0xaa1224, 0x118e0420)
        /home/pi/gopath/src/github.com/gogs/gogs/vendor/github.com/go-xorm/xorm/session_tx.go:10 +0xdc
github.com/gogs/gogs/vendor/github.com/go-xorm/xorm.(*Engine).DropTables(0x0, 0x11ced9d4, 0x1, 0x1, 0x0, 0x0)
        /home/pi/gopath/src/github.com/gogs/gogs/vendor/github.com/go-xorm/xorm/engine.go:1313 +0x5c
github.com/gogs/gogs/models.ImportDatabase(0x1199a840, 0x13, 0x0, 0x1199a800, 0x13)
        /home/pi/gopath/src/github.com/gogs/gogs/models/models.go:326 +0x2a0
github.com/gogs/gogs/cmd.runRestore(0x1192c460, 0x0, 0x0)
        /home/pi/gopath/src/github.com/gogs/gogs/cmd/restore.go:99 +0x5d4
github.com/gogs/gogs/vendor/github.com/urfave/cli.HandleAction(0x93f188, 0xaa05f4, 0x1192c460, 0x11b46600, 0x0)
        /home/pi/gopath/src/github.com/gogs/gogs/vendor/github.com/urfave/cli/app.go:483 +0x94
github.com/gogs/gogs/vendor/github.com/urfave/cli.Command.Run(0xa540d6, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa82386, 0x26, 0x0, ...)
        /home/pi/gopath/src/github.com/gogs/gogs/vendor/github.com/urfave/cli/command.go:193 +0x74c
github.com/gogs/gogs/vendor/github.com/urfave/cli.(*App).Run(0x11b440d0, 0x117240a0, 0x3, 0x4, 0x0, 0x0)
        /home/pi/gopath/src/github.com/gogs/gogs/vendor/github.com/urfave/cli/app.go:250 +0x4f4
main.main()
        /home/pi/gopath/src/github.com/gogs/gogs/gogs.go:40 +0x17c
```

Using the upgrade method (coping custom,data,log from previous version)
the web server stops after printing the version with no error
```
 $ ./gogs web
2019/09/02 04:54:10 [TRACE] Custom path: /home/git/gogs/custom
2019/09/02 04:54:10 [TRACE] Log path: /home/git/gogs/log
2019/09/02 04:54:10 [TRACE] Build Time: 2019-08-12 02:38:47 UTC
2019/09/02 04:54:10 [TRACE] Build Git Hash: c154721f4a8f3e24d2f6fb61e74b4b64529255c2
2019/09/02 04:54:10 [TRACE] Log Mode: File (Info)
2019/09/02 04:54:10 [ INFO] DinoDevs Gogs 0.11.91.0811
git@dinotron:~/gogs $ 
```

Logs:
`gogs.log`
```
$ cat /home/git/gogs/log/gogs.log
2019/09/02 04:34:09 [ INFO] DinoDevs Gogs 0.11.86.0130
2019/09/02 04:34:09 [ INFO] Cache Service Enabled
2019/09/02 04:34:09 [ INFO] Session Service Enabled
2019/09/02 04:34:09 [ INFO] Mail Service Enabled
2019/09/02 04:34:09 [ INFO] Register Mail Service Enabled
2019/09/02 04:34:09 [ INFO] Notify Mail Service Enabled
2019/09/02 04:34:09 [ INFO] Git Version: 2.11.0
2019/09/02 04:34:09 [ INFO] SQLite3 Supported
2019/09/02 04:34:09 [ INFO] Run Mode: Production
2019/09/02 04:34:10 [ INFO] Listen: http://0.0.0.0:8080
2019/09/02 04:35:03 [ INFO] DinoDevs Gogs 0.11.86.0130
2019/09/02 04:35:03 [ INFO] Cache Service Enabled
2019/09/02 04:35:03 [ INFO] Session Service Enabled
2019/09/02 04:35:03 [ INFO] Mail Service Enabled
2019/09/02 04:35:03 [ INFO] Register Mail Service Enabled
2019/09/02 04:35:03 [ INFO] Notify Mail Service Enabled
2019/09/02 04:35:03 [ INFO] Git Version: 2.11.0
2019/09/02 04:35:03 [ INFO] SQLite3 Supported
2019/09/02 04:35:03 [ INFO] Run Mode: Production
2019/09/02 04:35:05 [ INFO] Listen: http://0.0.0.0:8080
2019/09/02 04:54:10 [ INFO] DinoDevs Gogs 0.11.91.0811
2019/09/02 04:54:10 [ INFO] Cache Service Enabled
2019/09/02 04:54:10 [ INFO] Session Service Enabled
2019/09/02 04:54:10 [ INFO] Mail Service Enabled
2019/09/02 04:54:10 [ INFO] Register Mail Service Enabled
2019/09/02 04:54:10 [ INFO] Notify Mail Service Enabled
2019/09/02 04:54:10 [FATAL] [...gs/routes/install.go:66 GlobalInit()] Fail to initialize ORM engine: connect to database: this binary version does not build support for SQLite3
```

The `xorm.log` is empty

It seems like the `gogs_0.11.91_raspi_armv7.zip` has the SQLite disabled, maybe the SQLite was disabled by mistake on some the binary builds?

**Comment by unknwon** [comment]
Thanks @GramThanos, I'll post updates on #5790.

**Comment by GramThanos** [comment]
If @Routhgen 's logs show other error(s), he may reopen this.
