### ISSUE TITLE
'invalid memory address or nil pointer dereference' while merging pull request

### ISSUE THREAD

**Issue by rnentjes** [gogs/gogs#6401]
**Describe the bug**

While trying to merge a pull request in the user interface the server stops working. In the log I find the following error:

```
Oct 27 10:08:09 ns3008359 gogs[22868]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 27 10:08:09 ns3008359 gogs[22868]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe300a6]
Oct 27 10:08:09 ns3008359 gogs[22868]: goroutine 187753 [running]:
Oct 27 10:08:09 ns3008359 gogs[22868]: gogs.io/gogs/internal/db.(*Repository).getOwner(...)
Oct 27 10:08:09 ns3008359 gogs[22868]:         gogs.io/gogs/internal/db/repo.go:393
Oct 27 10:08:09 ns3008359 gogs[22868]: gogs.io/gogs/internal/db.(*Repository).mustOwner(0x0, 0x1fbe5e0, 0xc0006e6460, 0xc00018cdc0)
Oct 27 10:08:09 ns3008359 gogs[22868]:         gogs.io/gogs/internal/db/repo.go:406 +0x26
Oct 27 10:08:09 ns3008359 gogs[22868]: gogs.io/gogs/internal/db.(*Repository).repoPath(0x0, 0x1fbe5e0, 0xc0006e6460, 0x15b3a79, 0x44)
Oct 27 10:08:09 ns3008359 gogs[22868]:         gogs.io/gogs/internal/db/repo.go:526 +0x45
Oct 27 10:08:09 ns3008359 gogs[22868]: gogs.io/gogs/internal/db.(*Repository).RepoPath(...)
Oct 27 10:08:09 ns3008359 gogs[22868]:         gogs.io/gogs/internal/db/repo.go:530
Oct 27 10:08:09 ns3008359 gogs[22868]: gogs.io/gogs/internal/db.(*PullRequest).PushToBaseRepo(0xc0022162a0, 0x0, 0x0)
Oct 27 10:08:09 ns3008359 gogs[22868]:         gogs.io/gogs/internal/db/pull.go:674 +0x152
Oct 27 10:08:09 ns3008359 gogs[22868]: gogs.io/gogs/internal/db.addHeadRepoTasks(0xc0026ee010, 0x1, 0x2)
Oct 27 10:08:09 ns3008359 gogs[22868]:         gogs.io/gogs/internal/db/pull.go:766 +0x178
Oct 27 10:08:09 ns3008359 gogs[22868]: gogs.io/gogs/internal/db.AddTestPullRequestTask(0xc0025a4200, 0x18, 0xc00190cec0, 0x12, 0xc0007ecb00)
Oct 27 10:08:09 ns3008359 gogs[22868]:         gogs.io/gogs/internal/db/pull.go:811 +0x6fb
Oct 27 10:08:09 ns3008359 gogs[22868]: created by gogs.io/gogs/internal/db.(*PullRequest).Merge.func1
Oct 27 10:08:09 ns3008359 gogs[22868]:         gogs.io/gogs/internal/db/pull.go:200 +0xba
Oct 27 10:08:09 ns3008359 systemd[1]: gogs.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 27 10:08:09 ns3008359 systemd[1]: gogs.service: Failed with result 'exit-code'.
```

**Gogs version and commit**

Application version
    0.12.1
Git version
    2.17.1
Go version
    go1.15
Build time
    2020-08-27 07:07:30 UTC
Build commit
    43fc8260850090b55d4ee2586a819b3b6c016279 

**Operating system**

Ubuntu 18.04.5 LTS

**Database**

sqlite3

**To Reproduce**
1. Go to 'pull request.'
2. Click on 'merge pull request'
3. See error 503 (apache can't reach gogs anymore because it crashed, see log above)

**Can you reproduce the bug at https://try.gogs.io?**

No

**Expected behavior**

Page shows succesful merge message

**Actual behavior**

Apache http 503 error page

**Screenshots**

**Additional context**

Btw, this is code from repo.go:396, could this be the problem?:

```go
if repo.Owner != nil {
		return nil
	}
```

**Comment by zilkey** [comment]
I see this issue as well on version `0.11.97.1209`

Our database is PostgreSQL. Deployed in Kubernetes.
