### ISSUE TITLE
SIGSEGV panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jprante** [gogs/gogs#6577]
hudson.plugins.git.GitException: Command "/usr/bin/git fetch --tags --force --progress --prune -- origin +refs/heads/master:refs/remotes/origin/master" returned status code 128:
stdout: 
stderr: panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x804872]

goroutine 1 [running]:
unknwon.dev/clog/v2.(*fileLogger).deleteOutdatedFiles.func1(0xc000580150, 0x28, 0x0, 0x0, 0x1f94980, 0xc0003ba2a0, 0x0, 0x0)
	unknwon.dev/clog/v2@v2.1.2/file.go:104 +0x32
path/filepath.walk(0xc0004a2920, 0x14, 0x1fb6d80, 0xc000305e10, 0xc0002ab240, 0x0, 0xc0004a2920)
	path/filepath/path.go:380 +0x213
path/filepath.Walk(0xc0004a2920, 0x14, 0xc0002ab240, 0x14, 0x6)
	path/filepath/path.go:406 +0x105
unknwon.dev/clog/v2.(*fileLogger).deleteOutdatedFiles(0xc0002629a0, 0x13ae8a3, 0x2af0280)
	unknwon.dev/clog/v2@v2.1.2/file.go:103 +0x7c
unknwon.dev/clog/v2.(*fileLogger).initRotation(0xc0002629a0, 0x0, 0x0)
	unknwon.dev/clog/v2@v2.1.2/file.go:155 +0x15e
unknwon.dev/clog/v2.(*fileLogger).init(0xc0002629a0, 0xc000238120, 0x1d)
	unknwon.dev/clog/v2@v2.1.2/file.go:223 +0xb5
unknwon.dev/clog/v2.FileIniter.func1(0x15540ef, 0x4, 0xc0004a0660, 0x1, 0x1, 0x203000, 0x8, 0xc0004a2920, 0x420cd3)
	unknwon.dev/clog/v2@v2.1.2/file.go:271 +0x1ea
unknwon.dev/clog/v2.New(0x15540ef, 0x4, 0x1e48a78, 0xc0004a0660, 0x1, 0x1, 0xc0004bb501, 0xc0004a0660)
	unknwon.dev/clog/v2@v2.1.2/logger.go:145 +0x21c
unknwon.dev/clog/v2.NewFileWithName(0x15540ef, 0x4, 0xc0004a0660, 0x1, 0x1, 0x2af1700, 0x7f27ec73d108)
	unknwon.dev/clog/v2@v2.1.2/file.go:242 +0x65
unknwon.dev/clog/v2.NewFile(...)
	unknwon.dev/clog/v2@v2.1.2/file.go:236
gogs.io/gogs/internal/cmd.setup(0xc000034420, 0x155ceda, 0x8, 0x155a101)
	gogs.io/gogs/internal/cmd/serv.go:75 +0x2ee
gogs.io/gogs/internal/cmd.runServ(0xc000034420, 0x0, 0xc00000ed30)
	gogs.io/gogs/internal/cmd/serv.go:137 +0x5d
github.com/urfave/cli.HandleAction(0x139b4a0, 0x1e45ad8, 0xc000034420, 0xc000034420, 0x0)
	github.com/urfave/cli@v1.22.4/app.go:526 +0xfd
github.com/urfave/cli.Command.Run(0x1554493, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x15a5d15, 0x2f, 0x0, ...)
	github.com/urfave/cli@v1.22.4/command.go:174 +0x58e
github.com/urfave/cli.(*App).Run(0xc0001d61c0, 0xc00012a000, 0x4, 0x4, 0x0, 0x0)
	github.com/urfave/cli@v1.22.4/app.go:279 +0x7e8
main.main()
	gogs.io/gogs/gogs.go:39 +0x2e9

Name        : gogs
Version     : 0.12.3
Release     : 1602081439.b60e2c65.centos7
Architecture: x86_64
Install Date: Mi 17 Feb 2021 18:05:27 CET
Group       : default
Size        : 109394072
License     : unknown
Signature   : (none)
Source RPM  : gogs-0.12.3-1602081439.b60e2c65.centos7.src.rpm
Build Date  : Mi 07 Okt 2020 16:57:50 CEST
Build Host  : c5563b5df61c
Relocations : / 
Packager    : support@packager.io
Vendor      : Packager.io <https://packager.io>
URL         : http://example.com/no-uri-given
Summary     : Gogs is a painless self-hosted Git service
Description :
Gogs is a painless self-hosted Git service

**Comment by jianboy** [comment]
Me too.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7816bb]

goroutine 10 [running]:
unknwon.dev/clog/v2.(*fileLogger).deleteOutdatedFiles.func1({0xc002a1bea8, 0x16}, {0x0, 0x0}, {0xc00006fe40, 0x0})
        unknwon.dev/clog/v2@v2.1.2/file.go:104 +0x3b
path/filepath.walk({0xc00035ba40, 0xd}, {0x1cc4a38, 0xc00331af70}, 0xc00006fe40)
        path/filepath/path.go:438 +0x20d
path/filepath.Walk({0xc00035ba40, 0xd}, 0xc00006fe40)
        path/filepath/path.go:505 +0x6c
unknwon.dev/clog/v2.(*fileLogger).deleteOutdatedFiles(0xc0002133b0)
        unknwon.dev/clog/v2@v2.1.2/file.go:103 +0x4f
unknwon.dev/clog/v2.(*fileLogger).write(0xc0002133b0, {0x1cb0130, 0xc0023c31d0})
        unknwon.dev/clog/v2@v2.1.2/file.go:203 +0x41b
unknwon.dev/clog/v2.(*fileLogger).Write(0xc00006ffb0, {0x1cb0130, 0xc0023c31d0})
        unknwon.dev/clog/v2@v2.1.2/file.go:212 +0x25
unknwon.dev/clog/v2.New.func1()
        unknwon.dev/clog/v2@v2.1.2/logger.go:185 +0x62
created by unknwon.dev/clog/v2.New
        unknwon.dev/clog/v2@v2.1.2/logger.go:180 +0x575

```

**Comment by dennisvanderpool** [comment]
Same for me, multiple repo's. I think it's caused by DB corruption?

`PS C:\git\LeafletPOC> git push -u origin master                                                                                                                                                                                                                       Enumerating objects: 3, done.                                                                                                                                                                                                                                         Counting objects: 100% (3/3), done.                                                                                                                                                                                                                                   Delta compression using up to 32 threads                                                                                                                                                                                                                              Compressing objects: 100% (2/2), done.                                                                                                                                                                                                                                Writing objects: 100% (3/3), 1.15 KiB | 1.15 MiB/s, done.                                                                                                                                                                                                             Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)                                                                                                                                                                                                         remote: panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                                                                                       remote: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xea44f7]                                                                                                                                                                                        remote:                                                                                                                                                                                                                                                               remote: goroutine 1 [running]:                                                                                                                                                                                                                                        remote: gogs.io/gogs/internal/database.(*DB).Actions(...)                                                                                                                                                                                                             remote:         gogs.io/gogs/internal/database/database.go:161                                                                                                                                                                                                        remote: gogs.io/gogs/internal/database.PushUpdate({{0xc000693ef0, 0x28}, {0xc000693f20, 0x28}, {0xc000789b60, 0x11}, 0x1, {0xc00004e034, 0x6}, {0xc00004e015, ...}, ...})                                                                                             remote:         gogs.io/gogs/internal/database/update.go:130 +0x5f7                                                                                                                                                                                                   remote: gogs.io/gogs/internal/cmd.runHookPostReceive(0xc0003f31e0?)                                                                                                                                                                                                   remote:         gogs.io/gogs/internal/cmd/hook.go:229 +0x37d                                                                                                                                                                                                          remote: github.com/urfave/cli.HandleAction({0x13165e0?, 0x26c0810?}, 0xc?)                                                                                                                                                                                            remote:         github.com/urfave/cli@v1.22.14/app.go:524 +0x50                                                                                                                                                                                                       remote: github.com/urfave/cli.Command.Run({{0x152100b, 0xc}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x1549081, 0x1e}, {0x0, ...}, ...}, ...)                                                                                                                                   remote:         github.com/urfave/cli@v1.22.14/command.go:175 +0x63e                                                                                                                                                                                                  remote: github.com/urfave/cli.(*App).RunAsSubcommand(0xc000786c40, 0xc0003f2f20)                                                                                                                                                                                      remote:         github.com/urfave/cli@v1.22.14/app.go:405 +0xe07                                                                                                                                                                                                      remote: github.com/urfave/cli.Command.startApp({{0x150f006, 0x4}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x1561c9e, 0x2c}, {0x0, ...}, ...}, ...)                                                                                                                              remote:         github.com/urfave/cli@v1.22.14/command.go:380 +0xb58                                                                                                                                                                                                  remote: github.com/urfave/cli.Command.Run({{0x150f006, 0x4}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x1561c9e, 0x2c}, {0x0, ...}, ...}, ...)                                                                                                                                   remote:         github.com/urfave/cli@v1.22.14/command.go:103 +0x7e5                                                                                                                                                                                                  remote: github.com/urfave/cli.(*App).Run(0xc000786a80, {0xc000122100, 0x4, 0x4})                                                                                                                                                                                      remote:         github.com/urfave/cli@v1.22.14/app.go:277 +0xb27                                                                                                                                                                                                      remote: main.main()                                                                                                                                                                                                                                                   remote:         gogs.io/gogs/gogs.go:39 +0x405                                                                                                                                                                                                                        To http://gogs.lan:62667/Demon/LeafletPOC.git                                                                                                                                                                                                             * [new branch]      master -> master                                                                                                                                                                                                                                 branch 'master' set up to track 'origin/master'.         `
