### ISSUE TITLE
panic: look executable path: exec: "gogs": cannot run executable found relative to current directory

### ISSUE THREAD

**Issue by vuksavic** [gogs/gogs#7391]
### Gogs version

0.13.0

### Git version

git version 2.39.2.windows.1

### Operating system

Windows 10

### Database

MySQL 8.0

### Describe the bug

fresh download, successfully installed and created a new mysql server and databse, not really sure what's going on here
```
panic: look executable path: exec: "gogs": cannot run executable found relative to current directory

goroutine 1 [running]:
gogs.io/gogs/internal/conf.AppPath.func1()
        gogs.io/gogs/internal/conf/computed.go:39 +0x11b
sync.(*Once).doSlow(0x7ff6687946a2?, 0xc000458820?)
        sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        sync/once.go:65
gogs.io/gogs/internal/conf.AppPath()
        gogs.io/gogs/internal/conf/computed.go:35 +0x31
gogs.io/gogs/internal/conf.WorkDir.func1()
        gogs.io/gogs/internal/conf/computed.go:66 +0x58
sync.(*Once).doSlow(0x7ff66878ff82?, 0xc000287220?)
        sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        sync/once.go:65
gogs.io/gogs/internal/conf.WorkDir()
        gogs.io/gogs/internal/conf/computed.go:60 +0x31
gogs.io/gogs/internal/conf.CustomDir.func1()
        gogs.io/gogs/internal/conf/computed.go:87 +0x58
sync.(*Once).doSlow(0x0?, 0x0?)
        sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        sync/once.go:65
gogs.io/gogs/internal/conf.CustomDir()
        gogs.io/gogs/internal/conf/computed.go:81 +0x31
gogs.io/gogs/internal/conf.Init({0x0, 0x0})
        gogs.io/gogs/internal/conf/conf.go:64 +0x10e
gogs.io/gogs/internal/route.GlobalInit({0x0?, 0x4?})
        gogs.io/gogs/internal/route/install.go:51 +0x36
gogs.io/gogs/internal/cmd.runWeb(0xc00045c160)
        gogs.io/gogs/internal/cmd/web.go:166 +0x4e
github.com/urfave/cli.HandleAction({0x7ff66858bf40?, 0x7ff669930ea0?}, 0x3?)
        github.com/urfave/cli@v1.22.12/app.go:524 +0x50
github.com/urfave/cli.Command.Run({{0x7ff66877ea64, 0x3}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x7ff66879b1b4, 0x10}, {0x0, ...}, ...}, ...)
        github.com/urfave/cli@v1.22.12/command.go:175 +0x67b
github.com/urfave/cli.(*App).Run(0xc0000a21c0, {0xc00007a3c0, 0x2, 0x2})
        github.com/urfave/cli@v1.22.12/app.go:277 +0xb87
main.main()
        gogs.io/gogs/gogs.go:39 +0x428
```
exectuting `gogs` by itself supposedly works fine, shows info about gogs and some commands

### To reproduce

1. downloaded x64 zip with mws
2. open regular command prompt
3. point cmd to directory where gogs.exe is located, run `gogs web`

### Expected behavior

successful gogs boot 😅

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vuksavic** [comment]
> Having the same issue when I try `gogs backup`.

i've managed to "fix" this issue by instead of running `gogs web`, i just add .\ like this: `.\gogs.exe web`. i can only assume this works for every other gogs commmand. found the same issue in other go projects, apparently this started to happen with other golang projects compiled with go version 1.18
